spring:
  application:
    name:ltw-ai-code-mother
  main:
    banner-mode: off
  # DataSource Config
  datasource:
      url: jdbc:mysql://localhost:3306/ltw_ai_code_mother
      username: root
      password: 123456
  profiles:
    active: local
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.ltwaicodemother.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-flex:
  global-config:
    print-banner: false

#  langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
#  langchain4j.open-ai.chat-model.model-name=gpt-4o
#  langchain4j.open-ai.chat-model.log-requests=true
# 注释掉自动配置，使用 DeepSeekConfig 中的手动配置避免冲突
# langchain4j:
#   open-ai:
#     chat-model:
#       api-key: "e0f6ba72b57a4621b9bb2f7beac6c607"
#       model-name: "deepseek-chat"
